/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OhMyPassPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  autoLockMinutes: 5,
  clipboardClearSeconds: 30,
  defaultPasswordLength: 16,
  passwordCharset: "all"
};
var DEFAULT_DATA = {
  salt: null,
  verifyToken: null,
  vault: null,
  settings: { ...DEFAULT_SETTINGS }
};
var VIEW_TYPE_PASSWORD_LIST = "ohmypass-password-list";
var VERIFY_PLAINTEXT = "OHMYPASS_VERIFY_TOKEN_V1";

// src/crypto.ts
var PBKDF2_ITERATIONS = 6e5;
var SALT_LENGTH = 16;
var IV_LENGTH = 12;
function bufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = "";
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}
function base64ToBuffer(base64) {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes.buffer;
}
function generateSalt() {
  const salt = crypto.getRandomValues(new Uint8Array(SALT_LENGTH));
  return bufferToBase64(salt.buffer);
}
async function deriveKey(password, saltBase64) {
  const encoder = new TextEncoder();
  const keyMaterial = await crypto.subtle.importKey(
    "raw",
    encoder.encode(password),
    "PBKDF2",
    false,
    ["deriveKey"]
  );
  const salt = base64ToBuffer(saltBase64);
  return crypto.subtle.deriveKey(
    {
      name: "PBKDF2",
      salt,
      iterations: PBKDF2_ITERATIONS,
      hash: "SHA-256"
    },
    keyMaterial,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"]
  );
}
async function encrypt(plaintext, key) {
  const encoder = new TextEncoder();
  const iv = crypto.getRandomValues(new Uint8Array(IV_LENGTH));
  const ciphertext = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv },
    key,
    encoder.encode(plaintext)
  );
  return {
    iv: bufferToBase64(iv.buffer),
    ciphertext: bufferToBase64(ciphertext)
  };
}
async function decrypt(data, key) {
  try {
    const iv = base64ToBuffer(data.iv);
    const ciphertext = base64ToBuffer(data.ciphertext);
    const plainBuffer = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: new Uint8Array(iv) },
      key,
      ciphertext
    );
    return new TextDecoder().decode(plainBuffer);
  } catch (e) {
    return null;
  }
}

// src/store.ts
var PasswordStore = class {
  constructor(plugin) {
    this.data = { ...DEFAULT_DATA };
    this.key = null;
    this.entries = [];
    this.lastActivity = Date.now();
    this.plugin = plugin;
  }
  /** 加载持久化数据 */
  async load() {
    const saved = await this.plugin.loadData();
    if (saved) {
      this.data = { ...DEFAULT_DATA, ...saved };
    }
  }
  /** 保存持久化数据 */
  async save() {
    await this.plugin.saveData(this.data);
  }
  /** 是否首次使用（未设置主密码） */
  isFirstTime() {
    return this.data.salt === null;
  }
  /** 是否已解锁 */
  isUnlocked() {
    return this.key !== null;
  }
  /** 更新最后活动时间 */
  touch() {
    this.lastActivity = Date.now();
  }
  /** 检查是否应自动锁定 */
  shouldAutoLock() {
    const timeout = this.data.settings.autoLockMinutes * 60 * 1e3;
    return Date.now() - this.lastActivity > timeout;
  }
  /** 获取设置 */
  getSettings() {
    return this.data.settings;
  }
  /** 更新设置 */
  async updateSettings(partial) {
    this.data.settings = { ...this.data.settings, ...partial };
    await this.save();
  }
  // ── 主密码管理 ──
  /** 首次设置主密码 */
  async setup(password) {
    const salt = generateSalt();
    const key = await deriveKey(password, salt);
    const verifyToken = await encrypt(VERIFY_PLAINTEXT, key);
    this.data.salt = salt;
    this.data.verifyToken = verifyToken;
    this.data.vault = await encrypt(JSON.stringify([]), key);
    this.key = key;
    this.entries = [];
    this.touch();
    await this.save();
  }
  /** 用主密码解锁 */
  async unlock(password) {
    if (!this.data.salt || !this.data.verifyToken)
      return false;
    const key = await deriveKey(password, this.data.salt);
    const result = await decrypt(this.data.verifyToken, key);
    if (result !== VERIFY_PLAINTEXT)
      return false;
    this.key = key;
    if (this.data.vault) {
      const json = await decrypt(this.data.vault, key);
      this.entries = json ? JSON.parse(json) : [];
    } else {
      this.entries = [];
    }
    this.touch();
    return true;
  }
  /** 锁定（清除内存中的密钥和明文数据） */
  lock() {
    this.key = null;
    this.entries = [];
  }
  /** 修改主密码 */
  async changePassword(oldPassword, newPassword) {
    if (!this.data.salt)
      return false;
    const oldKey = await deriveKey(oldPassword, this.data.salt);
    const verify = await decrypt(this.data.verifyToken, oldKey);
    if (verify !== VERIFY_PLAINTEXT)
      return false;
    const newSalt = generateSalt();
    const newKey = await deriveKey(newPassword, newSalt);
    const newVerifyToken = await encrypt(VERIFY_PLAINTEXT, newKey);
    const newVault = await encrypt(JSON.stringify(this.entries), newKey);
    this.data.salt = newSalt;
    this.data.verifyToken = newVerifyToken;
    this.data.vault = newVault;
    this.key = newKey;
    this.touch();
    await this.save();
    return true;
  }
  // ── CRUD ──
  /** 获取所有条目 */
  getEntries() {
    return [...this.entries];
  }
  /** 按 ID 获取条目 */
  getEntry(id) {
    return this.entries.find((e) => e.id === id);
  }
  /** 添加条目 */
  async addEntry(entry) {
    const now = Date.now();
    const newEntry = {
      ...entry,
      id: this.generateId(),
      createdAt: now,
      updatedAt: now
    };
    this.entries.push(newEntry);
    await this.persistVault();
    this.touch();
    return newEntry;
  }
  /** 更新条目 */
  async updateEntry(id, updates) {
    const index = this.entries.findIndex((e) => e.id === id);
    if (index === -1)
      return false;
    this.entries[index] = {
      ...this.entries[index],
      ...updates,
      updatedAt: Date.now()
    };
    await this.persistVault();
    this.touch();
    return true;
  }
  /** 删除条目 */
  async deleteEntry(id) {
    const index = this.entries.findIndex((e) => e.id === id);
    if (index === -1)
      return false;
    this.entries.splice(index, 1);
    await this.persistVault();
    this.touch();
    return true;
  }
  /** 智能导入：批量添加条目并自动去重/标记冲突 */
  async importEntries(entries) {
    const exactSet = /* @__PURE__ */ new Set();
    const conflictSet = /* @__PURE__ */ new Set();
    for (const e of this.entries) {
      const baseKey = `${e.name}::${e.username}`;
      conflictSet.add(baseKey);
      exactSet.add(`${baseKey}::${e.password}`);
    }
    let added = 0;
    let skipped = 0;
    const now = Date.now();
    for (const entry of entries) {
      const baseKey = `${entry.name}::${entry.username}`;
      const exactKey = `${baseKey}::${entry.password}`;
      if (exactSet.has(exactKey)) {
        skipped++;
        continue;
      }
      if (conflictSet.has(baseKey)) {
        if (!entry.tags.includes("\u91CD\u590D\u6761\u76EE")) {
          entry.tags.push("\u91CD\u590D\u6761\u76EE");
        }
      }
      this.entries.push({
        ...entry,
        id: this.generateId(),
        createdAt: entry.createdAt || now,
        updatedAt: entry.updatedAt || now
      });
      exactSet.add(exactKey);
      conflictSet.add(baseKey);
      added++;
    }
    await this.persistVault();
    this.touch();
    return { added, skipped };
  }
  // ── 标签 ──
  /** 获取所有唯一标签（从条目中动态汇总） */
  getAllTags() {
    const tagSet = /* @__PURE__ */ new Set();
    for (const entry of this.entries) {
      for (const tag of entry.tags) {
        tagSet.add(tag);
        const parts = tag.split("/");
        for (let i = 1; i < parts.length; i++) {
          tagSet.add(parts.slice(0, i).join("/"));
        }
      }
    }
    return Array.from(tagSet).sort();
  }
  /** 构建标签树结构 */
  getTagTree() {
    const tags = this.getAllTags();
    const root = [];
    for (const tag of tags) {
      const parts = tag.split("/");
      let current = root;
      let path = "";
      for (const part of parts) {
        path = path ? `${path}/${part}` : part;
        let node = current.find((n) => n.name === part);
        if (!node) {
          node = { name: part, fullPath: path, children: [], count: 0 };
          current.push(node);
        }
        node.count = this.entries.filter(
          (e) => e.tags.some((t) => t === node.fullPath || t.startsWith(node.fullPath + "/"))
        ).length;
        current = node.children;
      }
    }
    return root;
  }
  // ── 搜索 ──
  /** 按关键词和标签过滤条目 */
  searchEntries(query, filterTag) {
    let results = this.entries;
    if (filterTag) {
      results = results.filter(
        (e) => e.tags.some((t) => t === filterTag || t.startsWith(filterTag + "/"))
      );
    }
    if (query.trim()) {
      const q = query.toLowerCase();
      results = results.filter(
        (e) => e.name.toLowerCase().includes(q) || e.username.toLowerCase().includes(q) || e.url && e.url.toLowerCase().includes(q) || e.notes && e.notes.toLowerCase().includes(q) || e.tags.some((t) => t.toLowerCase().includes(q))
      );
    }
    return results;
  }
  // ── 导出用：获取当前密钥 ──
  getKey() {
    return this.key;
  }
  getRawData() {
    return this.data;
  }
  // ── 内部方法 ──
  async persistVault() {
    if (!this.key)
      return;
    this.data.vault = await encrypt(JSON.stringify(this.entries), this.key);
    await this.save();
  }
  generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
  }
};

// src/views/PasswordListView.ts
var import_obsidian4 = require("obsidian");

// src/modals/AddEditModal.ts
var import_obsidian = require("obsidian");

// src/components/PasswordGenerator.ts
var CHARSETS = {
  lowercase: "abcdefghijklmnopqrstuvwxyz",
  uppercase: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  digits: "0123456789",
  special: "!@#$%^&*()_+-=[]{}|;:,.<>?"
};
function generatePassword(length, charset) {
  let chars = "";
  switch (charset) {
    case "all":
      chars = CHARSETS.lowercase + CHARSETS.uppercase + CHARSETS.digits + CHARSETS.special;
      break;
    case "alphanumeric":
      chars = CHARSETS.lowercase + CHARSETS.uppercase + CHARSETS.digits;
      break;
    case "alpha":
      chars = CHARSETS.lowercase + CHARSETS.uppercase;
      break;
    case "numeric":
      chars = CHARSETS.digits;
      break;
  }
  const array = new Uint32Array(length);
  crypto.getRandomValues(array);
  let result = "";
  for (let i = 0; i < length; i++) {
    result += chars[array[i] % chars.length];
  }
  return result;
}

// src/modals/AddEditModal.ts
var AddEditModal = class extends import_obsidian.Modal {
  constructor(app, store, onSave, existing) {
    super(app);
    this.tagsInput = "";
    this.store = store;
    this.onSave = onSave;
    this.isEdit = !!existing;
    if (existing) {
      this.entry = { ...existing };
      this.tagsInput = existing.tags.join(", ");
    } else {
      this.entry = { name: "", username: "", password: "", url: "", notes: "", tags: [] };
      this.tagsInput = "";
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("ohmypass-modal");
    contentEl.createEl("h2", { text: this.isEdit ? "\u270F\uFE0F \u7F16\u8F91\u5BC6\u7801" : "\u2795 \u6DFB\u52A0\u5BC6\u7801" });
    const errorEl = contentEl.createEl("p", { cls: "ohmypass-error" });
    new import_obsidian.Setting(contentEl).setName("\u670D\u52A1\u540D\u79F0").setDesc("\u5982 GitHub, Google, \u5FAE\u4FE1").addText((text) => {
      text.setValue(this.entry.name || "").setPlaceholder("\u670D\u52A1\u540D\u79F0").onChange((v) => {
        this.entry.name = v;
      });
    });
    new import_obsidian.Setting(contentEl).setName("\u7F51\u5740").addText((text) => {
      text.setValue(this.entry.url || "").setPlaceholder("https://example.com\uFF08\u53EF\u9009\uFF09").onChange((v) => {
        this.entry.url = v;
      });
    });
    new import_obsidian.Setting(contentEl).setName("\u7528\u6237\u540D / \u90AE\u7BB1").addText((text) => {
      text.setValue(this.entry.username || "").setPlaceholder("\u7528\u6237\u540D\u6216\u90AE\u7BB1").onChange((v) => {
        this.entry.username = v;
      });
    });
    const pwSetting = new import_obsidian.Setting(contentEl).setName("\u5BC6\u7801");
    let pwInput;
    pwSetting.addText((text) => {
      text.inputEl.type = "password";
      text.setValue(this.entry.password || "").setPlaceholder("\u5BC6\u7801").onChange((v) => {
        this.entry.password = v;
      });
      pwInput = text.inputEl;
    });
    pwSetting.addButton((btn) => {
      btn.setIcon("eye").setTooltip("\u663E\u793A/\u9690\u85CF\u5BC6\u7801").onClick(() => {
        pwInput.type = pwInput.type === "password" ? "text" : "password";
      });
    });
    pwSetting.addButton((btn) => {
      btn.setIcon("dice").setTooltip("\u751F\u6210\u968F\u673A\u5BC6\u7801").onClick(() => {
        const settings = this.store.getSettings();
        const pw = generatePassword(settings.defaultPasswordLength, settings.passwordCharset);
        this.entry.password = pw;
        pwInput.value = pw;
        pwInput.type = "text";
      });
    });
    const allTags = this.store.getAllTags();
    new import_obsidian.Setting(contentEl).setName("\u6807\u7B7E").setDesc('\u591A\u4E2A\u6807\u7B7E\u7528\u9017\u53F7\u5206\u9694\uFF0C\u652F\u6301\u5D4C\u5957\u5982 "\u5DE5\u4F5C/\u5185\u90E8"').addText((text) => {
      text.setValue(this.tagsInput).setPlaceholder("\u793E\u4EA4, \u5DE5\u4F5C/\u5185\u90E8\u7CFB\u7EDF").onChange((v) => {
        this.tagsInput = v;
      });
    });
    if (allTags.length > 0) {
      const tagContainer = contentEl.createDiv({ cls: "ohmypass-tag-suggestions" });
      tagContainer.createEl("small", { text: "\u5DF2\u6709\u6807\u7B7E\uFF08\u70B9\u51FB\u6DFB\u52A0\uFF09\uFF1A" });
      const tagList = tagContainer.createDiv({ cls: "ohmypass-tag-list" });
      for (const tag of allTags) {
        const tagEl = tagList.createEl("span", { text: tag, cls: "ohmypass-tag-chip" });
        tagEl.addEventListener("click", () => {
          var _a, _b;
          const current = this.tagsInput.split(",").map((s) => s.trim()).filter(Boolean);
          if (!current.includes(tag)) {
            current.push(tag);
            this.tagsInput = current.join(", ");
            const input = (_b = (_a = contentEl.querySelector(".ohmypass-tag-suggestions")) == null ? void 0 : _a.previousElementSibling) == null ? void 0 : _b.querySelector("input");
            if (input)
              input.value = this.tagsInput;
          }
        });
      }
    }
    new import_obsidian.Setting(contentEl).setName("\u5907\u6CE8").addTextArea((text) => {
      text.setValue(this.entry.notes || "").setPlaceholder("\u5907\u6CE8\u4FE1\u606F\uFF08\u53EF\u9009\uFF09").onChange((v) => {
        this.entry.notes = v;
      });
      text.inputEl.rows = 3;
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("\u53D6\u6D88").onClick(() => this.close());
    }).addButton((btn) => {
      btn.setButtonText(this.isEdit ? "\u4FDD\u5B58\u4FEE\u6539" : "\u6DFB\u52A0").setCta().onClick(async () => {
        var _a, _b, _c;
        if (!((_a = this.entry.name) == null ? void 0 : _a.trim())) {
          errorEl.setText("\u670D\u52A1\u540D\u79F0\u4E0D\u80FD\u4E3A\u7A7A");
          return;
        }
        if (!((_b = this.entry.username) == null ? void 0 : _b.trim())) {
          errorEl.setText("\u7528\u6237\u540D\u4E0D\u80FD\u4E3A\u7A7A");
          return;
        }
        if (!((_c = this.entry.password) == null ? void 0 : _c.trim())) {
          errorEl.setText("\u5BC6\u7801\u4E0D\u80FD\u4E3A\u7A7A");
          return;
        }
        const tags = this.tagsInput.split(",").map((s) => s.trim()).filter(Boolean);
        if (this.isEdit && this.entry.id) {
          await this.store.updateEntry(this.entry.id, {
            name: this.entry.name,
            url: this.entry.url,
            username: this.entry.username,
            password: this.entry.password,
            notes: this.entry.notes,
            tags
          });
        } else {
          await this.store.addEntry({
            name: this.entry.name,
            url: this.entry.url,
            username: this.entry.username,
            password: this.entry.password,
            notes: this.entry.notes,
            tags
          });
        }
        this.close();
        this.onSave();
      });
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/ConfirmDeleteModal.ts
var import_obsidian2 = require("obsidian");
var ConfirmDeleteModal = class extends import_obsidian2.Modal {
  constructor(app, entryName, onConfirm) {
    super(app);
    this.entryName = entryName;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("ohmypass-modal");
    contentEl.createEl("h2", { text: "\u26A0\uFE0F \u786E\u8BA4\u5220\u9664" });
    contentEl.createEl("p", {
      text: `\u786E\u5B9A\u8981\u5220\u9664 "${this.entryName}" \u7684\u5BC6\u7801\u8BB0\u5F55\u5417\uFF1F\u6B64\u64CD\u4F5C\u4E0D\u53EF\u64A4\u9500\u3002`
    });
    new import_obsidian2.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("\u53D6\u6D88").onClick(() => this.close());
    }).addButton((btn) => {
      btn.setButtonText("\u5220\u9664").setWarning().onClick(() => {
        this.close();
        this.onConfirm();
      });
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/ImportExportModal.ts
var import_obsidian3 = require("obsidian");

// src/importExport.ts
function entriesToCsv(entries) {
  const headers = ["name", "url", "username", "password", "notes", "tags"];
  const rows = entries.map((e) => [
    csvEscape(e.name),
    csvEscape(e.url || ""),
    csvEscape(e.username),
    csvEscape(e.password),
    csvEscape(e.notes || ""),
    csvEscape(e.tags.join(";"))
  ].join(","));
  return [headers.join(","), ...rows].join("\n");
}
function csvToEntries(csv) {
  var _a, _b, _c, _d, _e;
  const lines = csv.split("\n").filter((l) => l.trim());
  if (lines.length < 2)
    return [];
  const headers = parseCsvLine(lines[0]).map((h) => h.toLowerCase().trim());
  const nameIdx = findHeaderIndex(headers, ["name", "\u540D\u79F0", "\u670D\u52A1", "service", "title"]);
  const urlIdx = findHeaderIndex(headers, ["url", "\u7F51\u5740", "website", "link"]);
  const usernameIdx = findHeaderIndex(headers, ["username", "\u7528\u6237\u540D", "email", "\u90AE\u7BB1", "login", "user"]);
  const passwordIdx = findHeaderIndex(headers, ["password", "\u5BC6\u7801", "pass"]);
  const notesIdx = findHeaderIndex(headers, ["notes", "\u5907\u6CE8", "note", "comment", "comments"]);
  const tagsIdx = findHeaderIndex(headers, ["tags", "\u6807\u7B7E", "tag", "category", "\u5206\u7C7B", "folder", "group"]);
  const entries = [];
  for (let i = 1; i < lines.length; i++) {
    const cols = parseCsvLine(lines[i]);
    const name = nameIdx >= 0 ? (_a = cols[nameIdx]) == null ? void 0 : _a.trim() : "";
    const username = usernameIdx >= 0 ? (_b = cols[usernameIdx]) == null ? void 0 : _b.trim() : "";
    const password = passwordIdx >= 0 ? (_c = cols[passwordIdx]) == null ? void 0 : _c.trim() : "";
    if (!name && !username)
      continue;
    if (!name && !password)
      continue;
    if (!username && !password)
      continue;
    const url = urlIdx >= 0 ? (_d = cols[urlIdx]) == null ? void 0 : _d.trim() : "";
    let displayName = name;
    if (!displayName && url) {
      try {
        displayName = new URL(url).hostname;
      } catch (e) {
        displayName = url;
      }
    }
    entries.push({
      name: displayName || "Untitled",
      url: url || void 0,
      username: username || "",
      password: password || "",
      notes: notesIdx >= 0 ? (_e = cols[notesIdx]) == null ? void 0 : _e.trim() : void 0,
      tags: tagsIdx >= 0 ? (cols[tagsIdx] || "").split(";").map((s) => s.trim()).filter(Boolean) : []
    });
  }
  return entries;
}
async function exportEncryptedBackup(entries, password) {
  const salt = generateSalt();
  const key = await deriveKey(password, salt);
  const verifyToken = await encrypt("OHMYPASS_BACKUP_V1", key);
  const vault = await encrypt(JSON.stringify(entries), key);
  const backup = { version: 1, salt, verifyToken, vault };
  return JSON.stringify(backup, null, 2);
}
async function importEncryptedBackup(json, password) {
  try {
    const backup = JSON.parse(json);
    if (backup.version !== 1)
      return null;
    const key = await deriveKey(password, backup.salt);
    const verify = await decrypt(backup.verifyToken, key);
    if (verify !== "OHMYPASS_BACKUP_V1")
      return null;
    const vaultJson = await decrypt(backup.vault, key);
    if (!vaultJson)
      return null;
    return JSON.parse(vaultJson);
  } catch (e) {
    return null;
  }
}
function csvEscape(value) {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return '"' + value.replace(/"/g, '""') + '"';
  }
  return value;
}
function parseCsvLine(line) {
  const result = [];
  let current = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (inQuotes) {
      if (char === '"') {
        if (i + 1 < line.length && line[i + 1] === '"') {
          current += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        current += char;
      }
    } else {
      if (char === '"') {
        inQuotes = true;
      } else if (char === ",") {
        result.push(current);
        current = "";
      } else {
        current += char;
      }
    }
  }
  result.push(current);
  return result;
}
function findHeaderIndex(headers, candidates) {
  for (const candidate of candidates) {
    const idx = headers.indexOf(candidate);
    if (idx >= 0)
      return idx;
  }
  return -1;
}

// src/modals/ImportExportModal.ts
var ImportExportModal = class extends import_obsidian3.Modal {
  constructor(app, store, onDone) {
    super(app);
    this.store = store;
    this.onDone = onDone;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("ohmypass-modal");
    contentEl.createEl("h2", { text: "\u{1F4E6} \u5BFC\u5165 / \u5BFC\u51FA" });
    contentEl.createEl("h3", { text: "\u5BFC\u51FA" });
    new import_obsidian3.Setting(contentEl).setName("\u5BFC\u51FA\u4E3A CSV").setDesc("\u5BFC\u51FA\u6240\u6709\u5BC6\u7801\u4E3A\u660E\u6587 CSV \u6587\u4EF6\uFF08\u6CE8\u610F\u5B89\u5168\uFF01\uFF09").addButton((btn) => {
      btn.setButtonText("\u5BFC\u51FA CSV").setWarning().onClick(() => {
        const entries = this.store.getEntries();
        if (entries.length === 0) {
          new import_obsidian3.Notice("\u6CA1\u6709\u5BC6\u7801\u6761\u76EE\u53EF\u5BFC\u51FA");
          return;
        }
        const csv = entriesToCsv(entries);
        this.downloadFile("ohmypass_export.csv", csv, "text/csv");
        new import_obsidian3.Notice(`\u5DF2\u5BFC\u51FA ${entries.length} \u6761\u8BB0\u5F55`);
      });
    });
    new import_obsidian3.Setting(contentEl).setName("\u5BFC\u51FA\u52A0\u5BC6\u5907\u4EFD").setDesc("\u5BFC\u51FA\u4E3A\u52A0\u5BC6 JSON \u6587\u4EF6\uFF0C\u4F7F\u7528\u5F53\u524D\u4E3B\u5BC6\u7801\u52A0\u5BC6").addButton((btn) => {
      btn.setButtonText("\u5BFC\u51FA\u5907\u4EFD").onClick(async () => {
        const entries = this.store.getEntries();
        if (entries.length === 0) {
          new import_obsidian3.Notice("\u6CA1\u6709\u5BC6\u7801\u6761\u76EE\u53EF\u5BFC\u51FA");
          return;
        }
        new BackupPasswordModal(this.app, "\u5BFC\u51FA", async (password) => {
          const json = await exportEncryptedBackup(entries, password);
          this.downloadFile("ohmypass_backup.json", json, "application/json");
          new import_obsidian3.Notice(`\u5DF2\u52A0\u5BC6\u5BFC\u51FA ${entries.length} \u6761\u8BB0\u5F55`);
        }).open();
      });
    });
    contentEl.createEl("h3", { text: "\u5BFC\u5165" });
    new import_obsidian3.Setting(contentEl).setName("\u4ECE CSV \u5BFC\u5165").setDesc("\u652F\u6301\u4E3B\u6D41\u5BC6\u7801\u7BA1\u7406\u5668\u5BFC\u51FA\u7684 CSV \u683C\u5F0F").addButton((btn) => {
      btn.setButtonText("\u9009\u62E9 CSV \u6587\u4EF6").onClick(() => {
        this.pickFile(".csv", async (text) => {
          const entries = csvToEntries(text);
          if (entries.length === 0) {
            new import_obsidian3.Notice("\u672A\u80FD\u89E3\u6790\u4EFB\u4F55\u5BC6\u7801\u6761\u76EE\uFF0C\u8BF7\u68C0\u67E5 CSV \u683C\u5F0F");
            return;
          }
          const result = await this.store.importEntries(entries);
          let msg = `\u6210\u529F\u5BFC\u5165 ${result.added} \u6761\u8BB0\u5F55`;
          if (result.skipped > 0)
            msg += `\uFF0C\u8DF3\u8FC7 ${result.skipped} \u6761\u91CD\u590D\u8BB0\u5F55`;
          new import_obsidian3.Notice(msg);
          this.close();
          this.onDone();
        });
      });
    });
    new import_obsidian3.Setting(contentEl).setName("\u4ECE\u52A0\u5BC6\u5907\u4EFD\u5BFC\u5165").setDesc("\u5BFC\u5165 OhMyPass \u52A0\u5BC6\u5907\u4EFD\u6587\u4EF6").addButton((btn) => {
      btn.setButtonText("\u9009\u62E9\u5907\u4EFD\u6587\u4EF6").onClick(() => {
        this.pickFile(".json", async (text) => {
          new BackupPasswordModal(this.app, "\u5BFC\u5165", async (password) => {
            const entries = await importEncryptedBackup(text, password);
            if (!entries) {
              new import_obsidian3.Notice("\u5BFC\u5165\u5931\u8D25\uFF1A\u5BC6\u7801\u9519\u8BEF\u6216\u6587\u4EF6\u683C\u5F0F\u4E0D\u6B63\u786E");
              return;
            }
            const result = await this.store.importEntries(entries);
            let msg = `\u6210\u529F\u4ECE\u5907\u4EFD\u5BFC\u5165 ${result.added} \u6761\u8BB0\u5F55`;
            if (result.skipped > 0)
              msg += `\uFF0C\u8DF3\u8FC7 ${result.skipped} \u6761\u91CD\u590D\u8BB0\u5F55`;
            new import_obsidian3.Notice(msg);
            this.close();
            this.onDone();
          }).open();
        });
      });
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("\u5173\u95ED").onClick(() => this.close());
    });
  }
  downloadFile(filename, content, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }
  pickFile(accept, callback) {
    const input = document.createElement("input");
    input.type = "file";
    input.accept = accept;
    input.addEventListener("change", async () => {
      var _a;
      const file = (_a = input.files) == null ? void 0 : _a[0];
      if (!file)
        return;
      const text = await file.text();
      callback(text);
    });
    input.click();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var BackupPasswordModal = class extends import_obsidian3.Modal {
  constructor(app, action, onSubmit) {
    super(app);
    this.password = "";
    this.action = action;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("ohmypass-modal");
    contentEl.createEl("h2", { text: `\u{1F511} ${this.action}\u5BC6\u7801` });
    contentEl.createEl("p", {
      text: this.action === "\u5BFC\u51FA" ? "\u8BF7\u8BBE\u7F6E\u5907\u4EFD\u52A0\u5BC6\u5BC6\u7801\uFF08\u53EF\u4E0E\u4E3B\u5BC6\u7801\u4E0D\u540C\uFF09" : "\u8BF7\u8F93\u5165\u5907\u4EFD\u6587\u4EF6\u7684\u52A0\u5BC6\u5BC6\u7801"
    });
    new import_obsidian3.Setting(contentEl).setName("\u5BC6\u7801").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("\u52A0\u5BC6\u5BC6\u7801");
      text.onChange((v) => {
        this.password = v;
      });
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("\u786E\u8BA4").setCta().onClick(() => {
        if (!this.password)
          return;
        this.close();
        this.onSubmit(this.password);
      });
    });
  }
  onClose() {
    this.contentEl.empty();
    this.password = "";
  }
};

// src/views/PasswordListView.ts
var _PasswordListView = class extends import_obsidian4.ItemView {
  constructor(leaf, store, onRequestUnlock) {
    super(leaf);
    this.searchQuery = "";
    this.activeTag = null;
    this.clipboardTimers = [];
    this.expandedGroups = /* @__PURE__ */ new Set();
    this.searchDebounceTimer = null;
    this.visibleCount = 30;
    this.store = store;
    this.onRequestUnlock = onRequestUnlock;
  }
  getViewType() {
    return VIEW_TYPE_PASSWORD_LIST;
  }
  getDisplayText() {
    return "OhMyPass";
  }
  getIcon() {
    return "lock";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    for (const timer of this.clipboardTimers) {
      clearTimeout(timer);
    }
    this.clipboardTimers = [];
    if (this.searchDebounceTimer)
      clearTimeout(this.searchDebounceTimer);
  }
  /** 完整重新渲染 */
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ohmypass-view");
    if (!this.store.isUnlocked()) {
      this.renderLocked(container);
      return;
    }
    this.store.touch();
    this.renderToolbar(container);
    this.renderTagFilter(container);
    this.renderEntryList(container);
    this.renderStatusBar(container);
  }
  // ── 锁定状态 ──
  renderLocked(container) {
    const lockDiv = container.createDiv({ cls: "ohmypass-locked" });
    lockDiv.createEl("div", { text: "\u{1F512}", cls: "ohmypass-lock-icon" });
    lockDiv.createEl("p", { text: "\u5BC6\u7801\u5E93\u5DF2\u9501\u5B9A" });
    lockDiv.createEl("p", { text: "\u70B9\u51FB\u6B64\u5904\u89E3\u9501", cls: "ohmypass-hint ohmypass-unlock-link" });
    lockDiv.addEventListener("click", () => {
      this.onRequestUnlock();
    });
  }
  // ── 工具栏 ──
  renderToolbar(container) {
    const toolbar = container.createDiv({ cls: "ohmypass-toolbar" });
    const searchWrapper = toolbar.createDiv({ cls: "ohmypass-search-wrapper" });
    const searchInput = searchWrapper.createEl("input", {
      type: "text",
      placeholder: "\u{1F50D} \u641C\u7D22\u5BC6\u7801...",
      cls: "ohmypass-search"
    });
    searchInput.value = this.searchQuery;
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value;
      if (this.searchDebounceTimer)
        clearTimeout(this.searchDebounceTimer);
      this.searchDebounceTimer = window.setTimeout(() => {
        this.visibleCount = _PasswordListView.PAGE_SIZE;
        this.renderEntryList(container);
        this.renderStatusBar(container);
      }, 250);
    });
    const btnGroup = toolbar.createDiv({ cls: "ohmypass-btn-group" });
    const addBtn = btnGroup.createEl("button", { cls: "ohmypass-btn ohmypass-btn-primary" });
    (0, import_obsidian4.setIcon)(addBtn.createSpan(), "plus");
    addBtn.createSpan({ text: " \u6DFB\u52A0" });
    addBtn.addEventListener("click", () => {
      new AddEditModal(this.app, this.store, () => this.render()).open();
    });
    const importBtn = btnGroup.createEl("button", { cls: "ohmypass-btn" });
    (0, import_obsidian4.setIcon)(importBtn.createSpan(), "folder-input");
    importBtn.createSpan({ text: " \u5BFC\u5165/\u5BFC\u51FA" });
    importBtn.addEventListener("click", () => {
      new ImportExportModal(this.app, this.store, () => this.render()).open();
    });
    const lockBtn = btnGroup.createEl("button", { cls: "ohmypass-btn" });
    (0, import_obsidian4.setIcon)(lockBtn.createSpan(), "lock");
    lockBtn.createSpan({ text: " \u9501\u5B9A" });
    lockBtn.addEventListener("click", () => {
      this.store.lock();
      this.render();
    });
  }
  // ── 标签过滤 ──
  renderTagFilter(container) {
    const tags = this.store.getTagTree();
    if (tags.length === 0)
      return;
    const tagBar = container.createDiv({ cls: "ohmypass-tag-bar" });
    tagBar.createEl("span", { text: "\u6807\u7B7E\uFF1A", cls: "ohmypass-tag-label" });
    const allChip = tagBar.createEl("span", {
      text: "\u5168\u90E8",
      cls: `ohmypass-tag-chip ${this.activeTag === null ? "active" : ""}`
    });
    allChip.addEventListener("click", () => {
      this.activeTag = null;
      this.visibleCount = _PasswordListView.PAGE_SIZE;
      this.render();
    });
    this.renderTagNodes(tagBar, tags, 0);
  }
  renderTagNodes(parent, nodes, depth) {
    for (const node of nodes) {
      const chip = parent.createEl("span", {
        text: `${"\u3000".repeat(depth)}${node.name} (${node.count})`,
        cls: `ohmypass-tag-chip ${this.activeTag === node.fullPath ? "active" : ""}`
      });
      chip.addEventListener("click", () => {
        this.activeTag = this.activeTag === node.fullPath ? null : node.fullPath;
        this.visibleCount = _PasswordListView.PAGE_SIZE;
        this.render();
      });
      if (node.children.length > 0) {
        this.renderTagNodes(parent, node.children, depth + 1);
      }
    }
  }
  // ── 密码列表 ──
  renderEntryList(container) {
    const existing = container.querySelector(".ohmypass-entry-list");
    if (existing)
      existing.remove();
    const entries = this.store.searchEntries(this.searchQuery, this.activeTag || void 0);
    const list = container.createDiv({ cls: "ohmypass-entry-list" });
    if (entries.length === 0) {
      const empty = list.createDiv({ cls: "ohmypass-empty" });
      empty.createEl("div", { text: "\u{1F4ED}", cls: "ohmypass-empty-icon" });
      empty.createEl("p", { text: this.searchQuery ? "\u672A\u627E\u5230\u5339\u914D\u7684\u5BC6\u7801" : "\u8FD8\u6CA1\u6709\u4FDD\u5B58\u4EFB\u4F55\u5BC6\u7801" });
      return;
    }
    const groups = /* @__PURE__ */ new Map();
    for (const entry of entries) {
      const key = entry.name;
      if (!groups.has(key))
        groups.set(key, []);
      groups.get(key).push(entry);
    }
    const groupArray = Array.from(groups.entries());
    const visibleGroups = groupArray.slice(0, this.visibleCount);
    for (const [name, groupEntries] of visibleGroups) {
      if (groupEntries.length === 1) {
        this.renderEntryCard(list, groupEntries[0]);
      } else {
        this.renderGroup(list, name, groupEntries);
      }
    }
    if (groupArray.length > this.visibleCount) {
      const remaining = groupArray.length - this.visibleCount;
      const loadMoreBtn = list.createEl("button", {
        text: `\u52A0\u8F7D\u66F4\u591A\uFF08\u8FD8\u6709 ${remaining} \u9879\uFF09`,
        cls: "ohmypass-btn ohmypass-load-more"
      });
      loadMoreBtn.addEventListener("click", () => {
        this.visibleCount += _PasswordListView.PAGE_SIZE;
        this.renderEntryList(container);
      });
    }
  }
  /** 渲染同名服务分组（可折叠） */
  renderGroup(parent, name, entries) {
    const groupKey = name;
    const isExpanded = this.expandedGroups.has(groupKey);
    const groupEl = parent.createDiv({ cls: "ohmypass-group" });
    const header = groupEl.createDiv({ cls: `ohmypass-group-header ${isExpanded ? "expanded" : ""}` });
    const chevron = header.createSpan({ cls: "ohmypass-group-chevron" });
    (0, import_obsidian4.setIcon)(chevron, isExpanded ? "chevron-down" : "chevron-right");
    header.createSpan({ text: name, cls: "ohmypass-group-name" });
    header.createSpan({ text: `${entries.length} \u4E2A\u8D26\u53F7`, cls: "ohmypass-group-count" });
    if (!isExpanded) {
      const preview = header.createSpan({ cls: "ohmypass-group-preview" });
      const usernames = entries.map((e) => e.username).join(", ");
      preview.setText(usernames.length > 40 ? usernames.slice(0, 40) + "..." : usernames);
    }
    header.addEventListener("click", () => {
      if (this.expandedGroups.has(groupKey)) {
        this.expandedGroups.delete(groupKey);
      } else {
        this.expandedGroups.add(groupKey);
      }
      const container = this.containerEl.children[1];
      this.renderEntryList(container);
    });
    if (isExpanded) {
      const body = groupEl.createDiv({ cls: "ohmypass-group-body" });
      for (const entry of entries) {
        this.renderEntryCard(body, entry);
      }
    }
  }
  renderEntryCard(parent, entry) {
    const card = parent.createDiv({ cls: "ohmypass-card" });
    const header = card.createDiv({ cls: "ohmypass-card-header" });
    header.createEl("strong", { text: entry.name, cls: "ohmypass-card-name" });
    if (entry.tags.length > 0) {
      const tagsDiv = header.createDiv({ cls: "ohmypass-card-tags" });
      for (const tag of entry.tags) {
        tagsDiv.createEl("span", { text: tag, cls: "ohmypass-tag-badge" });
      }
    }
    const details = card.createDiv({ cls: "ohmypass-card-details" });
    if (entry.url) {
      const urlRow = details.createDiv({ cls: "ohmypass-card-row" });
      urlRow.createEl("span", { text: "\u{1F310}", cls: "ohmypass-card-icon" });
      const link = urlRow.createEl("a", { text: entry.url, href: entry.url });
      link.setAttr("target", "_blank");
    }
    const userRow = details.createDiv({ cls: "ohmypass-card-row" });
    userRow.createEl("span", { text: "\u{1F464}", cls: "ohmypass-card-icon" });
    userRow.createEl("span", { text: entry.username });
    const copyUserBtn = userRow.createEl("button", {
      cls: "ohmypass-icon-btn",
      attr: { "aria-label": "\u590D\u5236\u7528\u6237\u540D" }
    });
    (0, import_obsidian4.setIcon)(copyUserBtn, "copy");
    copyUserBtn.addEventListener("click", () => {
      navigator.clipboard.writeText(entry.username);
      new import_obsidian4.Notice("\u5DF2\u590D\u5236\u7528\u6237\u540D");
    });
    const pwRow = details.createDiv({ cls: "ohmypass-card-row" });
    pwRow.createEl("span", { text: "\u{1F511}", cls: "ohmypass-card-icon" });
    const pwDisplay = pwRow.createEl("code", { text: "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022", cls: "ohmypass-pw-display" });
    let pwVisible = false;
    const toggleBtn = pwRow.createEl("button", {
      cls: "ohmypass-icon-btn",
      attr: { "aria-label": "\u663E\u793A/\u9690\u85CF\u5BC6\u7801" }
    });
    (0, import_obsidian4.setIcon)(toggleBtn, "eye");
    toggleBtn.addEventListener("click", () => {
      pwVisible = !pwVisible;
      pwDisplay.setText(pwVisible ? entry.password : "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022");
      (0, import_obsidian4.setIcon)(toggleBtn, pwVisible ? "eye-off" : "eye");
    });
    const copyPwBtn = pwRow.createEl("button", {
      cls: "ohmypass-icon-btn",
      attr: { "aria-label": "\u590D\u5236\u5BC6\u7801" }
    });
    (0, import_obsidian4.setIcon)(copyPwBtn, "copy");
    copyPwBtn.addEventListener("click", () => {
      this.copyPassword(entry.password);
    });
    if (entry.notes) {
      const noteRow = details.createDiv({ cls: "ohmypass-card-row ohmypass-card-notes" });
      noteRow.createEl("span", { text: "\u{1F4DD}", cls: "ohmypass-card-icon" });
      noteRow.createEl("span", { text: entry.notes, cls: "ohmypass-note-text" });
    }
    const actions = card.createDiv({ cls: "ohmypass-card-actions" });
    const editBtn = actions.createEl("button", { cls: "ohmypass-btn ohmypass-btn-sm" });
    (0, import_obsidian4.setIcon)(editBtn.createSpan(), "pencil");
    editBtn.createSpan({ text: " \u7F16\u8F91" });
    editBtn.addEventListener("click", () => {
      new AddEditModal(this.app, this.store, () => this.render(), entry).open();
    });
    const deleteBtn = actions.createEl("button", { cls: "ohmypass-btn ohmypass-btn-sm ohmypass-btn-danger" });
    (0, import_obsidian4.setIcon)(deleteBtn.createSpan(), "trash");
    deleteBtn.createSpan({ text: " \u5220\u9664" });
    deleteBtn.addEventListener("click", () => {
      new ConfirmDeleteModal(this.app, entry.name, async () => {
        await this.store.deleteEntry(entry.id);
        this.render();
        new import_obsidian4.Notice(`\u5DF2\u5220\u9664 "${entry.name}"`);
      }).open();
    });
    const time = card.createDiv({ cls: "ohmypass-card-time" });
    time.createEl("small", {
      text: `\u66F4\u65B0\u4E8E ${new Date(entry.updatedAt).toLocaleDateString("zh-CN")}`
    });
  }
  // ── 状态栏 ──
  renderStatusBar(container) {
    const existing = container.querySelector(".ohmypass-status");
    if (existing)
      existing.remove();
    const total = this.store.getEntries().length;
    const filtered = this.store.searchEntries(this.searchQuery, this.activeTag || void 0).length;
    const status = container.createDiv({ cls: "ohmypass-status" });
    const text = total === filtered ? `\u5171 ${total} \u6761\u8BB0\u5F55` : `\u663E\u793A ${filtered} / ${total} \u6761\u8BB0\u5F55`;
    status.createEl("span", { text });
    status.createEl("span", { text: " \xB7 \u{1F513} \u5DF2\u89E3\u9501", cls: "ohmypass-status-unlock" });
  }
  // ── 剪贴板管理 ──
  copyPassword(password) {
    navigator.clipboard.writeText(password);
    new import_obsidian4.Notice("\u5DF2\u590D\u5236\u5BC6\u7801\uFF08\u5C06\u5728\u8BBE\u5B9A\u65F6\u95F4\u540E\u81EA\u52A8\u6E05\u9664\u526A\u8D34\u677F\uFF09");
    const clearSeconds = this.store.getSettings().clipboardClearSeconds;
    if (clearSeconds > 0) {
      const timer = window.setTimeout(() => {
        navigator.clipboard.writeText("").catch(() => {
        });
        new import_obsidian4.Notice("\u526A\u8D34\u677F\u5DF2\u81EA\u52A8\u6E05\u9664");
      }, clearSeconds * 1e3);
      this.clipboardTimers.push(timer);
    }
  }
};
var PasswordListView = _PasswordListView;
PasswordListView.PAGE_SIZE = 30;

// src/modals/SetupModal.ts
var import_obsidian5 = require("obsidian");
var SetupModal = class extends import_obsidian5.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.password = "";
    this.confirm = "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("ohmypass-modal");
    contentEl.createEl("h2", { text: "\u{1F510} \u8BBE\u7F6E\u4E3B\u5BC6\u7801" });
    contentEl.createEl("p", {
      text: "\u4E3B\u5BC6\u7801\u7528\u4E8E\u52A0\u5BC6\u4F60\u7684\u6240\u6709\u5BC6\u7801\u6570\u636E\u3002\u8BF7\u52A1\u5FC5\u7262\u8BB0\uFF0C\u9057\u5FD8\u540E\u6570\u636E\u4E0D\u53EF\u6062\u590D\u3002",
      cls: "ohmypass-modal-desc"
    });
    new import_obsidian5.Setting(contentEl).setName("\u4E3B\u5BC6\u7801").setDesc("\u81F3\u5C11 6 \u4E2A\u5B57\u7B26").addText((text) => {
      text.inputEl.type = "password";
      text.inputEl.placeholder = "\u8F93\u5165\u4E3B\u5BC6\u7801";
      text.onChange((v) => {
        this.password = v;
      });
    });
    new import_obsidian5.Setting(contentEl).setName("\u786E\u8BA4\u5BC6\u7801").addText((text) => {
      text.inputEl.type = "password";
      text.inputEl.placeholder = "\u518D\u6B21\u8F93\u5165\u4E3B\u5BC6\u7801";
      text.onChange((v) => {
        this.confirm = v;
      });
    });
    const errorEl = contentEl.createEl("p", { cls: "ohmypass-error" });
    new import_obsidian5.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("\u786E\u8BA4\u8BBE\u7F6E").setCta().onClick(() => {
        if (this.password.length < 6) {
          errorEl.setText("\u5BC6\u7801\u957F\u5EA6\u81F3\u5C11 6 \u4E2A\u5B57\u7B26");
          return;
        }
        if (this.password !== this.confirm) {
          errorEl.setText("\u4E24\u6B21\u8F93\u5165\u7684\u5BC6\u7801\u4E0D\u4E00\u81F4");
          return;
        }
        const pw = this.password;
        this.close();
        this.onSubmit(pw);
      });
    });
  }
  onClose() {
    this.contentEl.empty();
    this.password = "";
    this.confirm = "";
  }
};

// src/modals/UnlockModal.ts
var import_obsidian6 = require("obsidian");
var UnlockModal = class extends import_obsidian6.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.password = "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("ohmypass-modal");
    contentEl.createEl("h2", { text: "\u{1F513} \u89E3\u9501\u5BC6\u7801\u5E93" });
    contentEl.createEl("p", {
      text: "\u8F93\u5165\u4E3B\u5BC6\u7801\u4EE5\u8BBF\u95EE\u4F60\u7684\u5BC6\u7801\u6570\u636E\u3002",
      cls: "ohmypass-modal-desc"
    });
    const errorEl = contentEl.createEl("p", { cls: "ohmypass-error" });
    new import_obsidian6.Setting(contentEl).setName("\u4E3B\u5BC6\u7801").addText((text) => {
      text.inputEl.type = "password";
      text.inputEl.placeholder = "\u8F93\u5165\u4E3B\u5BC6\u7801";
      text.onChange((v) => {
        this.password = v;
      });
      text.inputEl.addEventListener("keydown", async (e) => {
        if (e.key === "Enter") {
          await this.tryUnlock(errorEl);
        }
      });
      setTimeout(() => text.inputEl.focus(), 50);
    });
    new import_obsidian6.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("\u89E3\u9501").setCta().onClick(async () => {
        await this.tryUnlock(errorEl);
      });
    });
  }
  async tryUnlock(errorEl) {
    if (!this.password) {
      errorEl.setText("\u8BF7\u8F93\u5165\u4E3B\u5BC6\u7801");
      return;
    }
    errorEl.setText("\u6B63\u5728\u9A8C\u8BC1...");
    const success = await this.onSubmit(this.password);
    if (!success) {
      errorEl.setText("\u5BC6\u7801\u9519\u8BEF\uFF0C\u8BF7\u91CD\u8BD5");
      this.password = "";
    } else {
      this.close();
    }
  }
  onClose() {
    this.contentEl.empty();
    this.password = "";
  }
};

// src/settings/SettingTab.ts
var import_obsidian7 = require("obsidian");
var OhMyPassSettingTab = class extends import_obsidian7.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "OhMyPass \u8BBE\u7F6E" });
    const settings = this.plugin.store.getSettings();
    new import_obsidian7.Setting(containerEl).setName("\u81EA\u52A8\u9501\u5B9A\u65F6\u95F4\uFF08\u5206\u949F\uFF09").setDesc("\u65E0\u64CD\u4F5C\u591A\u4E45\u540E\u81EA\u52A8\u9501\u5B9A\u5BC6\u7801\u5E93\uFF0C\u8BBE\u4E3A 0 \u7981\u7528").addText((text) => {
      text.setValue(String(settings.autoLockMinutes)).setPlaceholder("5").onChange(async (v) => {
        const num = parseInt(v) || 0;
        await this.plugin.store.updateSettings({ autoLockMinutes: Math.max(0, num) });
      });
      text.inputEl.type = "number";
    });
    new import_obsidian7.Setting(containerEl).setName("\u526A\u8D34\u677F\u6E05\u9664\u65F6\u95F4\uFF08\u79D2\uFF09").setDesc("\u590D\u5236\u5BC6\u7801\u540E\u591A\u5C11\u79D2\u81EA\u52A8\u6E05\u9664\u526A\u8D34\u677F\uFF0C\u8BBE\u4E3A 0 \u7981\u7528").addText((text) => {
      text.setValue(String(settings.clipboardClearSeconds)).setPlaceholder("30").onChange(async (v) => {
        const num = parseInt(v) || 0;
        await this.plugin.store.updateSettings({ clipboardClearSeconds: Math.max(0, num) });
      });
      text.inputEl.type = "number";
    });
    new import_obsidian7.Setting(containerEl).setName("\u9ED8\u8BA4\u5BC6\u7801\u957F\u5EA6").setDesc("\u968F\u673A\u751F\u6210\u5BC6\u7801\u7684\u9ED8\u8BA4\u957F\u5EA6").addText((text) => {
      text.setValue(String(settings.defaultPasswordLength)).setPlaceholder("16").onChange(async (v) => {
        const num = parseInt(v) || 16;
        await this.plugin.store.updateSettings({ defaultPasswordLength: Math.max(4, Math.min(128, num)) });
      });
      text.inputEl.type = "number";
    });
    new import_obsidian7.Setting(containerEl).setName("\u5BC6\u7801\u5B57\u7B26\u96C6").setDesc("\u968F\u673A\u751F\u6210\u5BC6\u7801\u5305\u542B\u7684\u5B57\u7B26\u7C7B\u578B").addDropdown((dd) => {
      dd.addOption("all", "\u5927\u5C0F\u5199 + \u6570\u5B57 + \u7279\u6B8A\u5B57\u7B26");
      dd.addOption("alphanumeric", "\u5927\u5C0F\u5199 + \u6570\u5B57");
      dd.addOption("alpha", "\u4EC5\u5B57\u6BCD");
      dd.addOption("numeric", "\u4EC5\u6570\u5B57");
      dd.setValue(settings.passwordCharset);
      dd.onChange(async (v) => {
        await this.plugin.store.updateSettings({
          passwordCharset: v
        });
      });
    });
    containerEl.createEl("h3", { text: "\u5B89\u5168" });
    new import_obsidian7.Setting(containerEl).setName("\u4FEE\u6539\u4E3B\u5BC6\u7801").setDesc("\u4FEE\u6539\u540E\u4F1A\u4F7F\u7528\u65B0\u5BC6\u7801\u91CD\u65B0\u52A0\u5BC6\u6240\u6709\u6570\u636E").addButton((btn) => {
      btn.setButtonText("\u4FEE\u6539\u4E3B\u5BC6\u7801").setWarning().onClick(() => {
        this.showChangePasswordUI(containerEl);
      });
    });
  }
  showChangePasswordUI(containerEl) {
    const div = containerEl.createDiv({ cls: "ohmypass-change-pw" });
    let oldPw = "", newPw = "", confirmPw = "";
    const errorEl = div.createEl("p", { cls: "ohmypass-error" });
    new import_obsidian7.Setting(div).setName("\u5F53\u524D\u5BC6\u7801").addText((text) => {
      text.inputEl.type = "password";
      text.onChange((v) => {
        oldPw = v;
      });
    });
    new import_obsidian7.Setting(div).setName("\u65B0\u5BC6\u7801").setDesc("\u81F3\u5C11 6 \u4E2A\u5B57\u7B26").addText((text) => {
      text.inputEl.type = "password";
      text.onChange((v) => {
        newPw = v;
      });
    });
    new import_obsidian7.Setting(div).setName("\u786E\u8BA4\u65B0\u5BC6\u7801").addText((text) => {
      text.inputEl.type = "password";
      text.onChange((v) => {
        confirmPw = v;
      });
    });
    new import_obsidian7.Setting(div).addButton((btn) => {
      btn.setButtonText("\u53D6\u6D88").onClick(() => div.remove());
    }).addButton((btn) => {
      btn.setButtonText("\u786E\u8BA4\u4FEE\u6539").setCta().onClick(async () => {
        if (newPw.length < 6) {
          errorEl.setText("\u65B0\u5BC6\u7801\u957F\u5EA6\u81F3\u5C11 6 \u4E2A\u5B57\u7B26");
          return;
        }
        if (newPw !== confirmPw) {
          errorEl.setText("\u4E24\u6B21\u8F93\u5165\u7684\u65B0\u5BC6\u7801\u4E0D\u4E00\u81F4");
          return;
        }
        const success = await this.plugin.store.changePassword(oldPw, newPw);
        if (success) {
          new import_obsidian7.Notice("\u4E3B\u5BC6\u7801\u4FEE\u6539\u6210\u529F");
          div.remove();
        } else {
          errorEl.setText("\u5F53\u524D\u5BC6\u7801\u9519\u8BEF");
        }
      });
    });
  }
};

// src/main.ts
var OhMyPassPlugin = class extends import_obsidian8.Plugin {
  constructor() {
    super(...arguments);
    this.store = new PasswordStore(this);
    this.autoLockInterval = null;
  }
  async onload() {
    await this.store.load();
    this.registerView(VIEW_TYPE_PASSWORD_LIST, (leaf) => {
      return new PasswordListView(leaf, this.store, () => this.handleUnlock());
    });
    this.addCommand({
      id: "open-password-vault",
      name: "\u6253\u5F00\u5BC6\u7801\u5E93",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "add-password",
      name: "\u6DFB\u52A0\u65B0\u5BC6\u7801",
      callback: () => {
        if (!this.store.isUnlocked()) {
          new import_obsidian8.Notice("\u8BF7\u5148\u89E3\u9501\u5BC6\u7801\u5E93");
          return;
        }
        new AddEditModal(this.app, this.store, () => this.refreshView()).open();
      }
    });
    this.addCommand({
      id: "unlock-vault",
      name: "\u89E3\u9501\u5BC6\u7801\u5E93",
      callback: () => this.handleUnlock()
    });
    this.addCommand({
      id: "lock-vault",
      name: "\u9501\u5B9A\u5BC6\u7801\u5E93",
      callback: () => {
        this.store.lock();
        this.refreshView();
        new import_obsidian8.Notice("\u5BC6\u7801\u5E93\u5DF2\u9501\u5B9A");
      }
    });
    this.addSettingTab(new OhMyPassSettingTab(this.app, this));
    this.addRibbonIcon("lock", "OhMyPass", () => {
      this.activateView();
    });
    this.autoLockInterval = window.setInterval(() => {
      if (this.store.isUnlocked() && this.store.shouldAutoLock()) {
        this.store.lock();
        this.refreshView();
        new import_obsidian8.Notice("\u5BC6\u7801\u5E93\u56E0\u8D85\u65F6\u5DF2\u81EA\u52A8\u9501\u5B9A");
      }
    }, 3e4);
    this.registerInterval(this.autoLockInterval);
  }
  onunload() {
    this.store.lock();
    if (this.autoLockInterval) {
      clearInterval(this.autoLockInterval);
    }
  }
  /** 激活密码库视图 */
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_PASSWORD_LIST);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: VIEW_TYPE_PASSWORD_LIST,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
    if (this.store.isFirstTime()) {
      this.handleSetup();
    } else if (!this.store.isUnlocked()) {
      this.handleUnlock();
    }
  }
  /** 首次设置主密码 */
  handleSetup() {
    new SetupModal(this.app, async (password) => {
      await this.store.setup(password);
      new import_obsidian8.Notice("\u4E3B\u5BC6\u7801\u8BBE\u7F6E\u6210\u529F\uFF01");
      this.refreshView();
    }).open();
  }
  /** 解锁密码库 */
  handleUnlock() {
    if (this.store.isFirstTime()) {
      this.handleSetup();
      return;
    }
    new UnlockModal(this.app, async (password) => {
      const success = await this.store.unlock(password);
      if (success) {
        new import_obsidian8.Notice("\u5BC6\u7801\u5E93\u5DF2\u89E3\u9501");
        this.refreshView();
      }
      return success;
    }).open();
  }
  /** 刷新视图 */
  refreshView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_PASSWORD_LIST);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof PasswordListView) {
        view.render();
      }
    }
  }
};
